### ISSUE TITLE
Family name should change for the variable version

### ISSUE THREAD

**Issue by jpamental** [googlefonts/literata#18]
When you run the build script to create the Variable Font versions, the family name is 'Literata 12pt Regular' (or 'Literata 12pt Italic') which then collides with the static font if you were to try an install them both. (not to mention that it doesn't make much sense to have that family name). I'd suggest that the build scripts should rename the resulting VF something like 'Literata Variable Upright' and 'Literata Variable Italic' so you can have it installed alongside the other static font files. (I don't know if this can be done in the build script or if it has to be done in the designspace files)

**Comment by davelab6** [comment]
If you were to try to install them both, you'd need to use a font manager to swap them in and out, or, make a custom build with the family name adjusted; since Google Fonts doesn't do versioning, and we want the variable functionality to be seen as standard, we don't change anything about the family names as they are updated with axes.
